# Introdução ao Python




## Declaração de variáveis

Para declarar variáveis em python utilizamos da sintáxe: 

nome = valor

Como por exemplo:


In [4]:
# inteiros:
idade = 35

# pontos flutuantes:
altura = 1.82

# strings:
nome = "Rodrigo"

# booleanos:
brasileiro = True

## Funções úteis

Dentre algumas funções, podemos destacar:
```python
input("mensagem opcional de entrada") # lê do stdin
print(valor) # escreve no stdout
int(minha_string) # transforma a string em inteiro
float(minha_string) # transforma a string em ponto flutuante```


In [15]:
# Printando valores:
print(idade)
print(altura)
print(nome)
print(brasileiro)

# Lendo valores:
meu_nome = input("Entre com seu nome:")

# '+' concatena duas strings:
print("Olá " +  meu_nome)


# Podemos usar 'aspas simples' ou "aspas duplas" para strings:
minha_idade = int(input('Entre com sua idade:'))

# Também podemos usar o próprio print para concatenar:
print('Sua idade é', minha_idade)

35
1.82
Rodrigo
True
Olá Felipe
Sua idade é 21


## Operadores aritméticos:

O Python oferece vários operadores que estamos familiarizados, tais como:
```python
soma = x + y
subtracao = x - y
multiplicacao = x * y
divisao = x / y
divisao_truncada = x // y # arredonda para baixo
exponenciacao = x ** y # x elevado a y
resto_divisao = x % y```

In [3]:
x = float(input("Entre com x: "))
y = float(input("Entre com y: "))

soma = x + y
subtracao = x - y
multiplicacao = x * y
divisao = x / y
divisao_truncada = x // y 
exponenciacao = x ** y
resto_divisao = x % y

print()

print("Soma:", soma)
print("Subtração:", subtracao)
print("Multiplicação:", multiplicacao)
print("Divisão:", divisao)
print("Divisão Truncada:", divisao_truncada)
print("Exponenciação:", exponenciacao)
print("Resto da Divisão:", resto_divisao)

Entre com x: 4
Entre com y: 5

Soma: 9.0
Subtração: -1.0
Multiplicação: 20.0
Divisão: 0.8
Divisão Truncada: 0.0
Exponenciação: 1024.0
Resto da Divisão: 4.0


## Estruturas de decisão e operadores de comparação e lógicos

Estruturas de decisão são recursos da linguagem que permitem ao programador fazer determinadas ações de acordo com um predicado. Elas têm a seguinte sintaxe:
```python
if (condicao1):
    comandos
elif condicao2:
    comandos
elif condicao3:
    comandos
else:
    comandos```
    
As condições devem ser coercíveis para `bool` para poderem ser executadas.

**Atenção! No Python, é necessário que os blocos estejam propriamente indentados, ou o interpretador irá lançar um erro.**

In [4]:
if True:
    print("Verdadeiro")
else:
    print("Absurdo")

Verdadeiro


### Operadores de comparação

Os operadores de comparação permitem verificar igualdades e desigualdades entre valores, sendo possível verificar se tal condição é verdadeira ou falsa. Dentre eles temos:
```python
igual = x == y
diferente = x != y
menor = x < y
maior = x > y
menor_igual = x <= y
maior_igual = x >= y```

### Operadores lógicos

Os operadores lógicos são operadores que recebem `bools` como argumento e retornam um `bool`. Dentre eles podem destacar:
```python
e_logico = x and y
ou_logico = x or y
nao_logico = not x```

Abaixo temos alguns exemplos de suas utilizações:

In [7]:
x = float(input("Entre com um valor: "))
y = float(input("Entre com outro valor: "))

if x > y:
    print(x, ">", y)
elif x == 10 or y == 10:
    print("Algum valor é igual a 10")
elif x < 0 and y < 0:
    print("Ambos os números são negativos")
else:
    print("Nenhum bloco acima foi executado")

Ambos os números são negativos


Em Python nós podemos também aninhar operadores de comparação:

In [8]:
x = float(input("Entre com um valor:"))

if 0 < x <= 10:
    print(x, "é maior que 0 e menor ou igual a 10")
elif -100 <= x <= 0:
    print(x, "está entre -100 e 0")
else:
    print(x, "é maior que 10 ou menor que -100")

Entre com um valor:50
50.0 é maior que 10 ou menor que -100


## Listas

No Python, podemos criar listas heterogêneas (isto é, listas podem conter qualquer tipo de variável). Por exemplo:

In [9]:
lista1 = ["Batata", 100, True]
print(lista1)

['Batata', 100, True]


| Tipo               | Mutável? | Indexável? | Pode conter tipos diferentes? | Usado para quê?                                | Exemplo                          |
|--------------------|----------|------------|-------------------------------|------------------------------------------------|----------------------------------|
| **Lista** (`list`) |  Sim   |   Sim     |  Sim                        | Estrutura genérica para armazenar dados        | `[1, 2, 'a', 3.0]`               |
| **Tupla** (`tuple`)|  Não   |   Sim     |  Sim                        | Dados fixos e imutáveis                        | `(1, 2, 'b')`                    |
| **Vetor** (conceito)| —        | —          | —                             | Termo genérico — pode ser uma lista ou array 1D| `[1, 2, 3]` ou `np.array([1,2,3])`|
| **Array** (`numpy.array`) |  Sim |  Sim |  Não (tipo fixo)            | Computação científica, álgebra linear          | `np.array([[1, 2], [3, 4]])`     |


### Métodos e funções úteis para listas

Para manipular listas, podemos destacar algumas funções e métodos úteis:

In [12]:
lista2 = [42, "Python", 3.14159, lista1]

# Tamanho de uma lista:
print("Tamanho da lista:", len(lista2))

# Adicionar um novo elemento:
lista2.append(1.88)
lista2.insert(2,False)
print("Lista com o novo elemento adicionado:", lista2)

# Acessando valores individuais:
print("Elemento na posição 0:", lista2[0]) # Pega o elemento na posição 0.
print("Último elemento:", lista2[-1]) # Pega o último elemento.
print("Penúltimo elemento:", lista2[-2]) # Pega o penúltimo elemento.
print("Elemento na posição 2 e 3:", lista2[2:4]) # Pega os elementos 2 e 3. Obs.: Primeiro valor incluso e último excluso.

# Reverter lista:
lista2.reverse()
print("Lista invertida:", lista2)

# Ordenação (para listas homogêneas):
lista3 = ['b', 'a', 'c']

lista3.sort()
print("Lista ordenada crescente:", lista3)

lista3.sort(reverse=True)
print("Lista ordenada decrescente:", lista3)

Tamanho da lista: 4
Lista com o novo elemento adicionado: [42, 'Python', False, 3.14159, ['Batata', 100, True], 1.88]
Elemento na posição 0: 42
Último elemento: 1.88
Penúltimo elemento: ['Batata', 100, True]
Elemento na posição 2 e 3: [False, 3.14159]
Lista invertida: [1.88, ['Batata', 100, True], 3.14159, False, 'Python', 42]
Lista ordenada crescente: ['a', 'b', 'c']
Lista ordenada decrescente: ['c', 'b', 'a']


## Estruturas de repetição

No Python, temos acesso a duas estruturas de repetição: `while` e `for`.

### while

Executa comandos dentro do bloco `while` enquanto a condição é verdadeira:

In [13]:
x = 512

while x > 0:
    print("x =", x)
    x //= 2 # o mesmo que x = x // 2

x = 512
x = 256
x = 128
x = 64
x = 32
x = 16
x = 8
x = 4
x = 2
x = 1


### for

Adicionamente, temos o `for`, que permite iterar por valores dentro de uma estrutura:

In [14]:
lista2 = [42, "Python", 3.14159]

for valor in lista2:
    print(valor)

42
Python
3.14159


In [15]:
print("[0, 5):")
for i in range(5):
    print(i)

print()
    
print("[2, 8):")
for j in range(2, 8):
    print(j)
    
print()
    
print("[4, 9) com passo 2:")
for k in range(4, 9, 2):
    print(k)

[0, 5):
0
1
2
3
4

[2, 8):
2
3
4
5
6
7

[4, 9) com passo 2:
4
6
8


## Tuplas

Tuplas funcionam como listas heterogêneas de tamanho fixo e imutáveis.

In [16]:
louis = ("Louis XIV", "França")
beethoven = ("Beethoven", "Alemanha")
aristoteles = ("Aristóteles", "Grécia")

# Acessando valores:
print(louis[0])

# Desconstrução de tuplas:
(nome1, pais1) = aristoteles
print(nome1, pais1)

Louis XIV
Aristóteles Grécia


## Funções

Funções fornecem uma forma de reutilizar código e deixar ele mais organizado. A sintaxe é como abaixo:
```python
def nome_funcao(argumento1, argumento2, argumento3=opcional1, argumento4=opcional2):
    corpo_funcao
    return valor # obs.: return não é obrigatório```

Abaixo temos exemplos de funções:

In [17]:
# Função com retorno:
def soma(x, y=5):
    z = x + y
    return z

print(soma(1, 3))
print(soma(3))

4
8


In [18]:
# Função sem retorno:
def mostra_paridade(valores):
    for valor in valores:
        if valor % 2 == 0:
            print(valor, "é par")
        else:
            print(valor, "é ímpar")
            
mostra_paridade(range(0, 10))

0 é par
1 é ímpar
2 é par
3 é ímpar
4 é par
5 é ímpar
6 é par
7 é ímpar
8 é par
9 é ímpar


## Arrays do NumPy
Embora as listas do Python sejam úteis para o desenvolvimento no dia-a-dia, daremos preferência aos arrays do NumPy, por serem mais eficientes e oferecerem mais operações úteis relacionadas à manipulação de vetores e matrizes algébricas.

O primeiro passo é importar o NumPy:

In [19]:
import numpy as np
# obs.: também poderíamos importar tudo do módulo:
# from numpy import *
# caso não tiver instalado utilizar o comando !pip install numpy

### Vetores

In [20]:
# Criação de vetores:
vetor = np.array([2, 3, 5, 7, 11])

#ou

# Shape mostra as dimensões do array:
print("Vetor:", vetor, "\nDimensão:", vetor.shape)

Vetor: [ 2  3  5  7 11] 
Dimensão: (5,)


In [21]:
# Também podemos especificar o tipo das variáveis dentro do array:
vetor_float = np.array([1, 0.1, 0.01, 0.001])
print("Vetor:", vetor_float, "   Dimensão:", vetor_float.shape, "   Tipo:", vetor_float.dtype)

print()

vetor_int = np.array([1, 1, 2, 3, 5, 8], np.uint8)
print("Vetor:", vetor_int, "               Dimensão:", vetor_int.shape, "   Tipo:", vetor_int.dtype)

Vetor: [1.    0.1   0.01  0.001]    Dimensão: (4,)    Tipo: float64

Vetor: [1 1 2 3 5 8]                Dimensão: (6,)    Tipo: uint8


### Matrizes

In [ ]:
# Criação de matrizes:
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

#ou

matriz_2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Matriz:\n", matriz, "\n\nDimensão:", matriz.shape)
print()
print("Matriz_2:\n", matriz_2, "\n\nDimensão:", matriz_2.shape)

Matriz:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Dimensão: (3, 3)

Matriz_2:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Dimensão: (3, 3)


### Funções e operações relevantes

#### Criação de arrays:

In [2]:
import numpy as np
print('Array tamanho 2x4 preenchido com 1:')
print(np.ones((2, 4)))

print('\nArray tamanho 2x4x3 preenchido com 0:')
print(np.zeros((3, 2, 4))) # Ordem invertida: [página, linha, coluna].

print('\nArray 3x4 com valores aleatórios em [0, 10):')
print(np.random.randint(10, size=(3, 4)))

print('\nArray com valores em [0, 1) e passo 0.1:')
print(np.arange(0, 1, 0.1))


Array tamanho 2x4 preenchido com 1:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Array tamanho 2x4x3 preenchido com 0:
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]

Array 3x4 com valores aleatórios em [0, 10):
[[7 2 7 0]
 [1 6 6 6]
 [9 7 6 8]]

Array com valores em [0, 1) e passo 0.1:
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#### Transposta e concatenação:

In [ ]:
matriz_2x3 = np.array([[0, 1, 2], 
                       [3, 4, 5]])

print('Matriz 2x3:')
print(matriz_2x3)

print('\nTransposta:')
print(matriz_2x3.T)

matriz_2x2 = np.array([[6, 7], 
                       [8, 9]])
print('\nMatriz 2x2:')
print(matriz_2x2)

matriz_3x3 = np.array([[6, 7, 8], 
                       [9, 10, 11], 
                       [12, 13, 14]])
print('\nMatriz 3x3:')
print(matriz_3x3)

print('\nMatriz 2x3 e Matriz 3x3 - Concatenação no eixo das linhas (eixo 0):')
print(np.concatenate([matriz_2x3, matriz_3x3], axis=0))

print('\nMatriz 2x3 e Matriz 2x2 - Concatenação no eixo das colunas (eixo 1):')
print(np.concatenate([matriz_2x3, matriz_2x2], axis=1))

Matriz 2x3:
[[0 1 2]
 [3 4 5]]

Transposta:
[[0 3]
 [1 4]
 [2 5]]

Matriz 2x2:
[[6 7]
 [8 9]]

Matriz 3x3:
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

Matriz 2x3 e Matriz 3x3 - Concatenação no eixo das linhas (eixo 0):
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

Matriz 2x3 e Matriz 2x2 - Concatenação no eixo das colunas (eixo 1):
[[0 1 2 6 7]
 [3 4 5 8 9]]


#### Indexação:

A indexação funciona da mesma forma que listas normais do Python:

In [26]:
# Elementos individuais:
matriz_4x3 = np.array([[0,  1,  2],
                       [3,  4,  5],
                       [6,  7,  8],
                       [9, 10, 11]])

print("Linha de índice 0:", matriz_4x3[0]) # linha de índice 0
print("Linha 2 e coluna 1:", matriz_4x3[2, 1]) # linha de índice 2 ([6, 7, 8]) e coluna de índice 1
print("Todas linhas e coluna 1:", matriz_4x3[:, 1]) # todas as linhas e coluna de índice 1
print("Linhas [1, 3) e colunas >= 1:\n", matriz_4x3[1:3, 1:]) # linhas [1, 3), todas as colunas a partir de 1
print(matriz_4x3.dtype)

Linha de índice 0: [0 1 2]
Linha 2 e coluna 1: 7
Todas linhas e coluna 1: [ 1  4  7 10]
Linhas [1, 3) e colunas >= 1:
 [[4 5]
 [7 8]]
int32


#### Operações:

In [ ]:
print('Multiplicação com escalar:')
print(np.ones((2, 3)) * 2)

print('\nSoma com escalar:')
print(np.zeros(6) + 3)

print('\nSoma ponto-a-ponto:')
# Equivalente a [[1, 1], [1, 1]] + [[10, 10], [10, 10]]:
print(np.ones((2, 2)) + 10 * np.ones((2, 2)))

print('\nMultiplicação ponto-a-ponto:')
# Equivalente a [2, 2, 2, 2] * [5, 5, 5, 5]:
print((2 * np.ones(4)) * (5 * np.ones(4)))

print('\nMultiplicação matricial:')
print(
np.matmul(
        np.array([[1, 2],
                  [3, 4]]),
        np.array([[5, 6],
                  [7, 8]])))

print('\nProduto escalar:')
#Equivalente a 1 * (-1) + 2 * 0 + 3 * 1:
print(np.dot(np.array([1, 2, 3]), np.array([-1, 0, 1])))

Multiplicação com escalar:
[[2. 2. 2.]
 [2. 2. 2.]]

Soma com escalar:
[3. 3. 3. 3. 3. 3.]

Soma ponto-a-ponto:
[[11. 11.]
 [11. 11.]]

Multiplicação ponto-a-ponto:
[10. 10. 10. 10.]

Multiplicação matricial:
[[19 22]
 [43 50]]

Produto escalar:
2
